### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by icio** [sherzberg/wercker-step-slack-notify#1]
You'll notice in the "environment variables" build step the following vars:

```
$export WERCKER_BUILD_URL="https://app.wercker.com/#build/..."
$export WERCKER_APPLICATION_URL="https://app.wercker.com/#applications/..."
```

It would be great if the payload sent to Slack contained hyperlinks to the successful/failed build and respective application using Slack's incoming-URL hyperlink format: `<http://URL|link title>` as per https://slack.com/services/new/incoming-webhook

**Comment by sherzberg** [comment]
closed with a48db7c45d7205a2a1f137
